# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'razorPay_paymentGateway' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for razorPay_paymentGateway

  target 'razorPay_paymentGatewayUITests' do
    # Pods for testing
  end
pod 'razorpay-pod'
end
